# Generated by Django 5.0.3 on 2024-03-18 21:20

import django.core.validators
import videoAPI.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('file', models.FileField(upload_to=videoAPI.models.video_upload_to, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4'])])),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
